### ISSUE TITLE
Support API Tokens for Cloudflare auth (safer than using Global API Keys)

### ISSUE THREAD

**Issue by chabad360** [jakejarvis/cloudflare-purge-action#1]
I've set all secrets correctly, yet I still get the following error:

```
Purge failed. API response was: 
{"success":false,"errors":[{"code":6003,"message":"Invalid request headers","error_chain":[{"code":6103,"message":"Invalid format for X-Auth-Key header"}]}],"messages":[],"result":null}
```

**Comment by jakejarvis** [comment]
Hmm, after searching around for that error code it seems like most people with this problem had a copy/paste typo with their API key — either only getting part of it or an extra space either before/after it, etc... I'd first try just deleting that secret and pasting it in again and let me know if that works.

The dashboard is not the most intuitive so make sure you're under My Profile (in the top right), then the API Tokens tab, and then press View for the Global API Key.

<img width="1053" alt="Screen Shot 2019-09-27 at 8 44 01 PM" src="https://user-images.githubusercontent.com/1703673/65809158-5d51c880-e168-11e9-8c76-650c22cb7a27.png">

I haven't looked into supporting API Tokens yet if that's what you're using — I assume they work the same but I've been meaning to try them myself since they announced them a few weeks ago.

Let me know if that doesn't help, sorry I don't have a more specific answer!

**Comment by chabad360** [comment]
Ah, thats it, I cant use API Tokens.

Would be nice if that could be added...

**Comment by jakejarvis** [comment]
Gotcha, sorry about that! I'll reopen this until I push an update 👍

**Comment by RobertClarke** [comment]
+1 on switching from a global API key to a permission-specific API token. Here's an example purge code using a token:

curl -X POST "https://api.cloudflare.com/client/v4/zones/********/purge_cache" \
     -H "Content-Type:application/json" \
     -H "Authorization: Bearer ********" \
     --data '{"purge_everything":true}'

It should be a simple change to make and removes the need to have the CLOUDFLARE_EMAIL secret. Hope this helps. :)
